### ISSUE TITLE
Feature request: Customizable chunk at encoding.

### ISSUE THREAD

**Issue by Qlex42** [Vidvox/hap-qt-codec#31]
Hi,

After installing QuickTime Hap codec for Windows, QuickTime based software like AfterEffect could only choose between pixel formats (Hap HapQ...)

It could be nice to benefit from the nice hap multi-chunk feature, and allowing the user to change the hard coded value from 1 chunk to another value in a "codec settings" dialog box.

A quicker solution could also to force 32 chunks for any hap. This let the decoder software decide how many thread it will allow to parallelize hap chunk decoding. This supposing that no CPU have more than 32 core today...

Thanks in advance for your concern about this issue.

**Comment by bangnoise** [comment]
Forcing 32 chunks would increase bitrate for small frame dimensions - chunking is only beneficial for fairly large frames.

Yes it would be nice to have the chunk count configurable, and an automatic mode which made a sensible decision by default.

**Comment by Qlex42** [comment]
Thanks for your reactivity,

You made a good point for the small frame dimensions and automatic mode.
But it do not seem trivial to implement.

I try to contribute to your source code, but sadly, I cannot manage to found deprecated QuickTime SDK for Windows... Apple seems to have removed it from all the Internet.

So I stay tuned for further hap-qt-codec development, 

Thanks again.

**Comment by bangnoise** [comment]
Just to note that the Hap encoder in ffmpeg has a configurable chunk setting.

**Comment by Qlex42** [comment]
Many thanks for that. 

But graphists people prefere after effect with quicktime codec than command line tools.

They also like to avoid additionnal rendering/conversion pass, especially with big video files.

Maybe there is a plugin on top of ffmpeg for rendering with all modern Adobe suite that do not relly on Quicktime for Windows ?

**Comment by bangnoise** [comment]
Yes that is just a note with some information for anyone who finds it useful. This issue is still open.

**Comment by Qlex42** [comment]
In fact FFmpeg do not use the libSquish for the DXT compression, but a simpler (quicker?) one. 
So hap-qt-codec have a so nicer result.
That's also why hap-qt-codec is promoted from graphists people against FFmpeg.
Great job !

Waiting for a nice dialog box, I temporary hard-code a chunk value in the source code for my needs.
Regards

**Comment by mkohlerworldstage** [comment]
I agree with @Qlex42 that this is an important enhancement, as  I cannot rely on using FFMPEG as my primary usage of HAP is as a delivery format from artists and designers who work primarily in the adobe suite. 

Adding an additional workflow step negates one of the key reasons HAP was so revolutionary to our workflow because media delivery is now no longer as simple as saying "download this codec and make us files" and the user experience of asking someone to install an additional utility and render all their files into an intermediary format and then retranscode using a command line utility is not acceptable.

So, I guess this is me +1-ing this feature request
