### ISSUE TITLE
Encoding Quality in FFMPEG 

### ISSUE THREAD

**Issue by tromerk** [Vidvox/hap-qt-codec#39]
I'm trying to understand why I am getting substantially worse results while encoding to HAP using FFMPEG vs. Adobe Media Encoder.  My problem is I need to do Chuncks encoding (which cannot be set using AME) but the results from FFMPEG are not up to quality.
See results here:
https://www.dropbox.com/s/4fakivsytefl60c/HAP%20Test.tif?dl=0
Here is my FF command line:
ffmpeg.exe -i "H:\_Render\test.mov" -vcodec hap -format hap_q "H:\_Render\output.mov"

AME is set to HAP Q, Quality=100, Render at Max Depth (not that any of those settings makes a difference if my understanding is correct).
Any ideas on how I can get the matching quality from FFMPEG or how ELSE I can do HAP encoding with Chunks ON WINDOWS?
Thanks!

**Comment by JonnyTech** [comment]
This works for me: 

`ffmpeg -i input.mov -vcodec hap -format hap_q -chunks 8 output.mov`

On Linux, but Windows should be the same

`ffmpeg version 3.2.4-1 Copyright (c) 2000-2017 the FFmpeg developers`

**Comment by tromerk** [comment]
Yes.  I can make it "work"   it's the quality i am questioning.   Looks much better when encoded with AME.



Keith Tromer
Corporate Imaging
845.365.0708


-------- Original message --------

**Comment by bangnoise** [comment]
This issue tracker is for the QuickTime codec. Please post issues with ffmpeg to their [bug tracker](http://ffmpeg.org/bugreports.html).

The Hap Q compressor in ffmpeg is different from the one in this codec, and of fixed quality. There are no settings which can affect its output.

**Comment by tromerk** [comment]
OK.  Sorry for choosing the wrong place.   And I agree - this is NOT a bug with HAP qt codec.

Would you mind shedding some more light on the encoding process for me?  So, when I install the QT codec, it adds a feature to encode using quicktime.  This encoding processed is used when:  Exporting from QT Pro, using Adobe Media Encoder, After Effects, (I am sure many other).  BUT when using FFMPEG they have written their own engine for encoding to HAP?  

Do I have all that correct?  I did not realize that FFMPEG would/should encode at a different quality.  

OK - is there a way HAP encoded with chunks properly (because obviously FFMPEG does not do such a good job)?

Thanks much.

**Comment by PeterSchuebel** [comment]
That is basically correct, Keith.

Many Windows or MacOS based applications such as After Effects etc use video codec conversions via QuickTime (QT) plugins, so that any newly installed QT plugin on a system can be used by them. This obviously works only on operating systems that support QT. Please be also aware that Apple no longer supports the QuickTime player on Windows (https://support.apple.com/kb/DL837?locale=en_US), i.e. they will not provide updates for the player anymore.

FFmpeg on the other hand is a very cross-platform set of libraries and tools, that can be built for many more operating systems, including Windows, MacOS, and most Linux and Unix flavours.
FFmpeg also supports many additional video and audio codecs for which no QuickTime plugin exists at all.
Moreover, their decision to not support system-wide QuickTime plugins may be based on restrictions of licensing or other reasons of who controls the actual plugin code (e.g. HAP in this case). So they decided to re-implement HAP support themselves.
When you post a bug report on the FFmpeg tracker, it'll be important to provide all relevant settings for AME and FFmpeg and clearly describe the difference in quality (e.g. what kind of visual artifacts appear), so they know what to look for. Providing your example outputs (as you did here) is also a good idea.

**Comment by bangnoise** [comment]
Many people find the encoder in FFmpeg to be adequate, though obviously for this particular frame it is inferior.

Another alternative on macOS is [AVF Batch Converter](https://github.com/Vidvox/hap-in-avfoundation/releases) which allows chunked encoding. Its encoders are based on those used in the QuickTime codec.

You may also want to open a bug with the [libav bug tracker](https://libav.org/bugreports/) - the encoder in FFmpeg was originally written there, so your bug report may receive more attention, and any changes should eventually find their way back into FFmpeg.

**Comment by tromerk** [comment]
Thanks for the replies.

I have filed a report to the libav bug tracker.  If I hear anything, I'll reply back here.
-kt

**Comment by JonnyTech** [comment]
Can you provide a link to the bug report for reference here please?

**Comment by tromerk** [comment]
I submitted at the link given above.  But I got a message back saying:

INVALID

This is not the FFmpeg issue tracker.

**Comment by JonnyTech** [comment]
For libav too?
