### ISSUE TITLE
Previewing HAP Alpha files in QT7 and MPEG Streamclip produce artifacts

### ISSUE THREAD

**Issue by ejoflow** [Vidvox/hap-qt-codec#41]
Noticed that when I load HAP (with Alpha) encoded files into Quicktime7 or MPEG Streamclip, there is extra color information that is being produced. I'm unable to convert these files properly with a matted black background. Export produces the same color artifacts. In the files below you will see what the HAP with Alpha looks like (top) and the expected result.

<img width="640" alt="screen shot 2017-08-24 at 10 23 15 am" src="https://user-images.githubusercontent.com/31319936/29679331-5aeb2c88-88b6-11e7-823f-d4ad1e7b72d8.png">
<img width="640" alt="screen shot 2017-08-24 at 10 23 43 am" src="https://user-images.githubusercontent.com/31319936/29679330-5ab7d540-88b6-11e7-8a6e-865a546cf61e.png">

**Comment by Sunsneezer** [comment]
That looks to me like what happens when you render stuff with **straight alpha** this stuff is meant to make semi-transparent pixels the same color instead of being contaminated by the background color. The effect is dramatic because of the very wide glow going on, spreading the semi transparent pixels far and wide.

Quicktime 7 and MPEG streamclip must not be displaying the video using the alpha channel as I don't think they support it. Try importing this file into After Effects to verify it and I bet it will be all right. If you never need this video to be on top on bright stuff, or need a file that works without the alpha you can use premultiplied alpha.

https://www.provideocoalition.com/alpha-channels-premultiplied-vs-straight/

**Comment by bangnoise** [comment]
Closing this. If you believe this is due to an issue in the Hap QT codec please add more information about the steps taken to encode your files.
