### ISSUE TITLE
video thready

### ISSUE THREAD

**Issue by vjdobermann** [Vidvox/hap-qt-codec#45]
Hi all,

I'm testing HAP, on After Effect I created a 30sec video (1024x578) with HAP codec.

When using it on Modul8 (vj'ing program) the video is very thready, it won't be possible to use this on a live performance...
I haven't any issues with other codec before...

**Comment by bangnoise** [comment]
I'm not sure what you mean by "thready" but if you are describing a performance issue within Modul8, you should pursue that with the Modul8 folks - they will provide support for their product. If you think "thready" is something to do with this codec then re-open the issue with more details.

**Comment by vjdobermann** [comment]
apologize, english isn't my mother tongue...
maybe "jerky" is a synonym of "thready" ?

Modul8 is based on quicktime codecs, so if a codec has an issue, Modul8 wont't be able to read the video file.
The support answer is simple : stop using this codec xD

**Comment by bangnoise** [comment]
Jerky makes sense.

If that's their advice for Modul8 then follow it - it's up to individual applications to add support for Hap.

If an application uses QuickTime for playback but doesn't have support for accelerated Hap then decoding is done in software and playback will be slow - the codec is only able to provide accelerated playback if the application requests it (because the frames have to be handled differently).

A common cause of jerky playback when accelerated Hap playback is supported is insufficient bandwidth from disk - e.g. playing from a hard drive.
