### ISSUE TITLE
Massive file size inflation encoding H.264 1080p MP4 to HAP Q MOV

### ISSUE THREAD

**Issue by wwwerk** [Vidvox/hap-qt-codec#47]
Encoded via AVF Batch encoder
Similar results on these same files with HAP and HAP Q
Resulting files play back in QT but are enormous:
310 MB to 63 GB 
7.2 MB to 822.1 MB

System: MacPro (Late 2013) 64 GB RAM, 2.7 GHz 12 core Xeon, AMD FirePro D700 6144 MB
OSX 10.12.6

Finder screenshot for filesize comparison attached.

Two source files linked here:
http://files.justinmorrison.net/dropbox/hap/

![hap encode screen shot 2018-06-15 at 6 32 15 pm](https://user-images.githubusercontent.com/10946317/41494634-be0d592e-70ca-11e8-9377-77537ca0c292.png)

**Comment by dlublin** [comment]
Hey wwwerk!

With a quick test we weren't able to recreate this issue and we haven't had any similar reports about this yet.

A few quick things...

1. As a minor detail, if you are using the AVF Batch Exporter, the appropriate place for issues would be its project page,
https://github.com/Vidvox/hap-in-avfoundation/issues
(no biggie, but for future reference it does makesit easier for us to track issues)

As a follow up to this, I am curious if you get similar results when using the QuickTime exporter, eg with QuickTime Player 7 Pro.


2. We don't have the same exact test machine: we have a similar Mac Pro, but it's running 10.13 instead of 10.12. I'm not aware of any OS-dependent discrepancies, but I thought this worth mentioning regardless. Testing on a Macbook Pro in both 10.12 & 10.13 we were also not able to recreate this.


3. We're using the 'Chandelier Dance.mp4' file you provided, which I'm assuming is the 310 MB file you referred to in your issue. We transcoded the above file using the AVF batch converter available here: https://github.com/Vidvox/hap-in-avfoundation/releases/download/1.5.3/AVF.Batch.Converter.app.zip

The resulting hap file is only 1.93 GB, and the hapQ file is only 3.97 GB.  This is a substantial discrepancy from the 63 GB file you quoted.

As a side note, we also tried a much older version of the AVF batch converter to transcode the files, and the files it produced had the same size as the files produced by the latest build of the batch converter.


Finally, feel free to follow up with us on email about this (support@vidvox.net). If you can send us a screenshot of the specific setting you are using from the exporter app and the specific version that you were using that'd also be great!

- DL

**Comment by wwwerk** [comment]
1) Ah, thank you for the tip. If necessary, we can move this thread to the AVF issue cue (I can repost).

2) First, I'll update to 10.13 on the MacPro and re-run an encode. 

3) I realized I neglected to provide an AVF version. Since the package I have doesn't include a version number (About AVF Batch Converter), I can't guarantee but I'm pretty sure I pulled the latest release: 1.5.3. Since I'm re-running this, I'll double confirm

In the meantime: I've re-ran the job with my current setup. I'll do this again after checking the above, but results were the same: 63.2 GB files from a 310 MB source, no difference whether setting highest or lowest quality setting (screenshot includes Finder and HQ and LQ file names, respectively)

![screen shot 2018-06-21 at 6 30 56 pm](https://user-images.githubusercontent.com/10946317/41753383-ef9a4630-7581-11e8-8df7-94f52124f408.png)

![screen shot 2018-06-21 at 6 28 04 pm](https://user-images.githubusercontent.com/10946317/41753389-fab9a632-7581-11e8-8032-d31a314994e6.png)

![screen shot 2018-06-21 at 6 32 53 pm](https://user-images.githubusercontent.com/10946317/41753393-040b1d92-7582-11e8-894b-ab5e3040aabe.png)

![screen shot 2018-06-21 at 6 33 06 pm](https://user-images.githubusercontent.com/10946317/41753398-0b171d7a-7582-11e8-8d7d-16906eebe5cf.png)

**Comment by dlublin** [comment]
Hi Justin-

Thanks to the information you sent us, we figured out how to reproduce this issue and I think we've fixed it.  We've uploaded a new version of the batch exporter, which is linked to below- please give that a shot, and if you're still having problems just re-open this issue.

https://github.com/Vidvox/hap-in-avfoundation/releases/tag/1.6.8

**Comment by bangnoise** [comment]
Closing this here as it's an AVF issue

**Comment by wwwerk** [comment]
Thank you David. I'll test and resubmit to the AVF repo if the issue persists.
