### ISSUE TITLE
Mac warns of incompatibilities with future versions of MacOS

### ISSUE THREAD

**Issue by craigreilly** [Vidvox/hap-qt-codec#48]
Perhaps due to 64bit requirement.

**Comment by bangnoise** [comment]
Yes.

**Comment by dlublin** [comment]
Note that the AVFoundation codebase for working with HAP can be found here: https://github.com/vidvox/hap-in-avfoundation

**Comment by craigreilly** [comment]
not sure what I do with this? I'm just looking to load 64-bit HAP Codec for
conversion from other formats.

**Comment by bangnoise** [comment]
Sorry for the slow reply @craigreilly - the repo @dlublin linked to hosts the [AVF Batch Converter](https://github.com/Vidvox/hap-in-avfoundation/releases) which can be used to convert to Hap - otherwise there are other options including ffmpeg or the [Hap exporter for Adobe Premiere & Media Encoder]((https://github.com/disguise-one/hap-adobe-premiere-plugin/releases)) currently in alpha. The Hap site has [some others](http://hap.video/integrations.html#encoding) too as well as a [guide for encoding](http://hap.video/using-hap.html).

You probably worked all this out months ago - just adding it for future readers.
